In [675]:
# 필요한 라이브러리 설치 (처음 한 번만 실행)
!pip install numpy pandas matplotlib seaborn scipy scikit-learn statsmodels pingouin scikit_posthocs xgboost -q

print("라이브러리 설치 완료!")

라이브러리 설치 완료!

In [676]:
# 데이터 처리 및 분석
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import warnings

# 시각화
import matplotlib.pyplot as plt
import seaborn as sns

# 통계 분석
from scipy import stats
from scipy.stats import shapiro, levene, ttest_ind, chi2_contingency, f_oneway
from scipy.stats import mannwhitneyu, fisher_exact, kruskal
from statsmodels.stats.multicomp import pairwise_tukeyhsd, MultiComparison
import pingouin as pg
import scikit_posthocs as sp

# 출력 설정
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# 한글 폰트 설정
import platform
if platform.system() == 'Windows':
    plt.rcParams['font.family'] = 'Malgun Gothic'
elif platform.system() == 'Darwin':  # macOS
    plt.rcParams['font.family'] = 'AppleGothic'
else:  # Linux
    plt.rcParams['font.family'] = 'NanumGothic'

plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['figure.figsize'] = (12, 6)

# 시드 설정
np.random.seed(42)

print("="*60)
print("라이브러리 로드 완료!")
print("한글 폰트 설정 완료!")
print("="*60)

============================================================
라이브러리 로드 완료!
한글 폰트 설정 완료!
============================================================

In [677]:
customers = pd.read_csv('data/olist_customers_dataset.csv')

In [678]:
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [679]:
customers.duplicated(subset='customer_id',keep=False).sum()

np.int64(0)

In [680]:
customers['customer_city'] = customers['customer_city'].replace('')

In [681]:
customers.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [682]:
geolocation = pd.read_csv('data/olist_geolocation_dataset.csv')

In [683]:
geolocation

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [684]:
geolocation.duplicated(subset='geolocation_zip_code_prefix',keep=False).sum()
# np.int64(999120)

np.int64(999120)

In [685]:
geolocation.sort_values(by='geolocation_zip_code_prefix')

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
1246,1001,-23.549292,-46.633559,sao paulo,SP
429,1001,-23.550498,-46.634338,sao paulo,SP
1182,1001,-23.549779,-46.633957,sao paulo,SP
1435,1001,-23.549292,-46.633559,sao paulo,SP
326,1001,-23.551427,-46.634074,sao paulo,SP
...,...,...,...,...,...
1000026,99980,-28.388679,-51.848863,david canabarro,RS
999950,99980,-28.388400,-51.845225,david canabarro,RS
1000002,99980,-28.388342,-51.845194,david canabarro,RS
999864,99990,-28.329472,-51.769109,muliterno,RS
999758,99990,-28.329718,-51.769615,muliterno,RS

In [686]:
geolocation['geolocation_lat'] = geolocation['geolocation_lat'].round(2)
geolocation['geolocation_lng'] = geolocation['geolocation_lng'].round(2)
geolocation = geolocation.sort_values(by=['geolocation_zip_code_prefix','geolocation_lat','geolocation_lng'],ascending=[True,False,False])
geolocation

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
99,1001,-23.55,-46.63,sao paulo,SP
206,1001,-23.55,-46.63,sao paulo,SP
235,1001,-23.55,-46.63,sao paulo,SP
299,1001,-23.55,-46.63,sao paulo,SP
326,1001,-23.55,-46.63,sao paulo,SP
...,...,...,...,...,...
1000133,99980,-28.39,-51.85,david canabarro,RS
1000161,99980,-28.39,-51.85,david canabarro,RS
999976,99980,-28.42,-51.78,david canabarro,RS
999758,99990,-28.33,-51.77,muliterno,RS
999864,99990,-28.33,-51.77,muliterno,RS

In [687]:
geolocation = geolocation.drop_duplicates(subset='geolocation_zip_code_prefix',keep='first')
geolocation['geolocation_city'] = geolocation['geolocation_city'].replace('ã','a')
geolocation

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
99,1001,-23.55,-46.63,sao paulo,SP
1251,1002,-23.54,-46.63,são paulo,SP
478,1003,-23.55,-46.63,são paulo,SP
278,1004,-23.55,-46.63,sao paulo,SP
584,1005,-23.55,-46.63,são paulo,SP
...,...,...,...,...,...
999784,99960,-27.95,-52.02,charrua,RS
999754,99965,-28.17,-52.04,agua santa,RS
999787,99970,-28.34,-51.87,ciriaco,RS
999897,99980,-28.39,-51.84,david canabarro,RS
999758,99990,-28.33,-51.77,muliterno,RS

In [688]:
geolocation.isna().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [689]:
order_items = pd.read_csv('data/olist_order_items_dataset.csv')

In [690]:
order_items[order_items['order_id'].duplicated(keep=False)]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
13,0008288aa423d2a3f00fcb17cd7d8719,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37
14,0008288aa423d2a3f00fcb17cd7d8719,2,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37
32,00143d0f86d6fbd9f9b38ab440ac16f5,1,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10
33,00143d0f86d6fbd9f9b38ab440ac16f5,2,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10
34,00143d0f86d6fbd9f9b38ab440ac16f5,3,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10
...,...,...,...,...,...,...,...
112635,fff8287bbae429a99bb7e8c21d151c41,2,bee2e070c39f3dd2f6883a17a5f0da45,4e922959ae960d389249c378d1c939f5,2018-03-27 12:29:22,180.00,48.14
112640,fffb9224b6fc7c43ebb0904318b10b5f,1,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112641,fffb9224b6fc7c43ebb0904318b10b5f,2,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112642,fffb9224b6fc7c43ebb0904318b10b5f,3,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112643,fffb9224b6fc7c43ebb0904318b10b5f,4,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19

In [691]:
order_items[order_items['order_id']=='02355020fd0a40a0d56df9f6ff060413']

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
947,02355020fd0a40a0d56df9f6ff060413,1,a3daee3915d4fb98376e039ede6bdea6,2a261b5b644fa05f4f2700eb93544f2c,2018-03-08 02:15:42,50.0,19.59

In [692]:
order_reviews = pd.read_csv('data/olist_order_reviews_dataset.csv')

In [693]:
order_reviews[order_reviews['order_id']=='02355020fd0a40a0d56df9f6ff060413']

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
17582,017f0e1ea6386de662cbeba299c59ad1,02355020fd0a40a0d56df9f6ff060413,1,NaN,ja reclamei varias vezes e ate hoje não sei on...,2018-03-29 00:00:00,2018-03-30 03:16:19
89888,0c8e7347f1cdd2aede37371543e3d163,02355020fd0a40a0d56df9f6ff060413,3,NaN,UM DOS PRODUTOS (ENTREGA02) COMPRADOS NESTE PE...,2018-03-21 00:00:00,2018-03-22 01:32:08

In [694]:
order_reviews[order_reviews['order_id'].duplicated(keep=False)].sort_values(by=['order_id'])

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
25612,89a02c45c340aeeb1354a24e7d4b2c1e,0035246a40f520710769010f752e7507,5,NaN,NaN,2017-08-29 00:00:00,2017-08-30 01:59:12
22423,2a74b0559eb58fc1ff842ecc999594cb,0035246a40f520710769010f752e7507,5,NaN,Estou acostumada a comprar produtos pelo barat...,2017-08-25 00:00:00,2017-08-29 21:45:57
22779,ab30810c29da5da8045216f0f62652a2,013056cfe49763c6f66bda03396c5ee3,5,NaN,NaN,2018-02-22 00:00:00,2018-02-23 12:12:30
68633,73413b847f63e02bc752b364f6d05ee9,013056cfe49763c6f66bda03396c5ee3,4,NaN,NaN,2018-03-04 00:00:00,2018-03-05 17:02:00
854,830636803620cdf8b6ffaf1b2f6e92b2,0176a6846bcb3b0d3aa3116a9a768597,5,NaN,NaN,2017-12-30 00:00:00,2018-01-02 10:54:06
...,...,...,...,...,...,...,...
27465,5e78482ee783451be6026e5cf0c72de1,ff763b73e473d03c321bcd5a053316e8,3,NaN,Não sei que haverá acontecido os demais chegaram,2017-11-18 00:00:00,2017-11-18 09:02:48
41355,39de8ad3a1a494fc68cc2d5382f052f4,ff850ba359507b996e8b2fbb26df8d03,5,NaN,Envio rapido... Produto 100%,2017-08-16 00:00:00,2017-08-17 11:56:55
18783,80f25f32c00540d49d57796fb6658535,ff850ba359507b996e8b2fbb26df8d03,5,NaN,"Envio rapido, produto conforme descrito no anu...",2017-08-22 00:00:00,2017-08-25 11:40:22
92230,870d856a4873d3a67252b0c51d79b950,ffaabba06c9d293a3c614e0515ddbabc,3,NaN,NaN,2017-12-20 00:00:00,2017-12-20 18:50:16
53962,5476dd0eaee7c4e2725cafb011aa758c,ffaabba06c9d293a3c614e0515ddbabc,3,NaN,NaN,2017-12-20 00:00:00,2017-12-21 13:24:55

In [695]:
order_items[order_items['order_id']=='0544030711e50ec2cb6c15764d22891a']

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
2319,0544030711e50ec2cb6c15764d22891a,1,8d12ee985749e3ea570ed7f5c875479a,d91fb3b7d041e83b64a00a3edfb37e4f,2018-04-19 02:30:43,14.3,18.23

In [696]:
order_reviews[order_reviews['order_id']=='0544030711e50ec2cb6c15764d22891a']

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
49073,dc7a14d3e1984bfc11b484b841697096,0544030711e50ec2cb6c15764d22891a,4,Não quero avaliar,NaN,2018-05-01 00:00:00,2018-05-04 11:29:18
79041,72906dc18cd7aaed26be40c859613c65,0544030711e50ec2cb6c15764d22891a,1,É muito confusa.,Comprei duas válvulas solenóides iguais. Pague...,2018-05-01 00:00:00,2018-05-04 17:54:45

In [697]:
order_items[order_items['order_id']=='14f6c86b695ea4ddd3dd4386d10388b0']

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
9164,14f6c86b695ea4ddd3dd4386d10388b0,1,1d79cdcf69371b7e6e8ab6831d2c6483,d91fb3b7d041e83b64a00a3edfb37e4f,2017-06-13 14:25:18,21.0,9.27

In [698]:
order_reviews[order_reviews['order_id']=='14f6c86b695ea4ddd3dd4386d10388b0']

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
4412,6c3c56231c45f130228a386e4d9b124a,14f6c86b695ea4ddd3dd4386d10388b0,5,NaN,NaN,2017-06-13 00:00:00,2017-06-14 11:47:49
15280,948c1093fc5e0db2081ce9f9b4a1bf82,14f6c86b695ea4ddd3dd4386d10388b0,5,NaN,NaN,2017-06-13 00:00:00,2017-06-14 11:48:09

In [699]:
order_items.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [700]:
dup_item = order_items[order_items.duplicated(subset='order_id',keep=False)].sort_values(by=['order_id','order_item_id'],ascending=[True,False])
dup_item

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
14,0008288aa423d2a3f00fcb17cd7d8719,2,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37
13,0008288aa423d2a3f00fcb17cd7d8719,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37
34,00143d0f86d6fbd9f9b38ab440ac16f5,3,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10
33,00143d0f86d6fbd9f9b38ab440ac16f5,2,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10
32,00143d0f86d6fbd9f9b38ab440ac16f5,1,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10
...,...,...,...,...,...,...,...
112634,fff8287bbae429a99bb7e8c21d151c41,1,bee2e070c39f3dd2f6883a17a5f0da45,4e922959ae960d389249c378d1c939f5,2018-03-27 12:29:22,180.00,48.14
112643,fffb9224b6fc7c43ebb0904318b10b5f,4,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112642,fffb9224b6fc7c43ebb0904318b10b5f,3,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112641,fffb9224b6fc7c43ebb0904318b10b5f,2,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112640,fffb9224b6fc7c43ebb0904318b10b5f,1,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19

In [701]:
# order_items = order_items.sort_values(by=['order_id','order_item_id'],ascending=[True,False])
# print(f"중복 처리 전 order_items 행 수: {len(order_items)}")
# order_items = order_items.drop_duplicates(subset='order_id',keep='first')
# print(f"중복 처리 후 order_items 행 수: {len(order_items)}")
# 중복 처리 전 order_items 행 수: 112650
# 중복 처리 후 order_items 행 수: 98666

In [702]:
order_payments = pd.read_csv('data/olist_order_payments_dataset.csv')

In [703]:
order_payments

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [704]:
order_payments.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [705]:
dup_pay = order_payments[order_payments.duplicated(subset=['order_id','payment_sequential'],keep=False)].sort_values(by=['order_id','payment_sequential'])
dup_pay

Empty DataFrame
Columns: [order_id, payment_sequential, payment_type, payment_installments, payment_value]
Index: []

In [706]:
order_reviews = pd.read_csv('data/olist_order_reviews_dataset.csv')

In [707]:
order_reviews

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [708]:
dup_rev = order_reviews[order_reviews.duplicated(subset='review_id',keep=False)].sort_values(by='review_id')
dup_rev

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
46678,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
29841,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
90677,0115633a9c298b6a98bcbe4eee75345f,78a4201f58af3463bdab842eea4bc801,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
63193,0115633a9c298b6a98bcbe4eee75345f,0c9850b2c179c1ef60d2855e2751d1fa,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
92876,0174caf0ee5964646040cd94e15ac95e,f93a732712407c02dce5dd5088d0f47b,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07 00:00:00,2018-03-08 03:00:53
...,...,...,...,...,...,...,...
31120,fe5c833752953fed3209646f1f63b53c,4863e15fa53273cc7219c58f5ffda4fb,1,NaN,"Comprei dois produtos e ambos, mesmo enviados ...",2018-02-28 00:00:00,2018-02-28 13:57:52
7870,ff2fc9e68f8aabfbe18d710b83aabd30,2da58e0a7dcfa4ce1e00fad9d03ca3b5,2,NaN,NaN,2018-03-17 00:00:00,2018-03-19 11:44:15
82521,ff2fc9e68f8aabfbe18d710b83aabd30,1078d496cc6ab9a8e6f2be77abf5091b,2,NaN,NaN,2018-03-17 00:00:00,2018-03-19 11:44:15
73951,ffb8cff872a625632ac983eb1f88843c,c44883fc2529b4aa03ca90e7e09d95b6,3,NaN,NaN,2017-07-22 00:00:00,2017-07-26 13:41:07
1985,ffb8cff872a625632ac983eb1f88843c,c88b1d1b157a9999ce368f218a407141,3,NaN,NaN,2017-07-22 00:00:00,2017-07-26 13:41:07

In [709]:
orders = pd.read_csv('data/olist_orders_dataset.csv')

In [710]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [711]:
orders[orders['order_delivered_customer_date']>orders['order_estimated_delivery_date']]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
20,203096f03d82e0dffbc41ebc2e2bcfb7,d2b091571da224a1b36412c18bc3bbfe,delivered,2017-09-18 14:31:30,2017-09-19 04:04:09,2017-10-06 17:50:03,2017-10-09 22:23:46,2017-09-28 00:00:00
25,fbf9ac61453ac646ce8ad9783d7d0af6,3a874b4d4c4b6543206ff5d89287f0c3,delivered,2018-02-20 23:46:53,2018-02-22 02:30:46,2018-02-26 22:25:22,2018-03-21 22:03:54,2018-03-12 00:00:00
35,8563039e855156e48fccee4d611a3196,5f16605299d698660e0606f7eae2d2f9,delivered,2018-02-17 15:59:46,2018-02-17 16:15:34,2018-02-20 23:03:56,2018-03-20 00:59:25,2018-03-20 00:00:00
41,6ea2f835b4556291ffdc53fa0b3b95e8,c7340080e394356141681bd4c9b8fe31,delivered,2017-11-24 21:27:48,2017-11-25 00:21:09,2017-12-13 21:14:05,2017-12-28 18:59:23,2017-12-21 00:00:00
57,66e4624ae69e7dc89bd50222b59f581f,684fa6da5134b9e4dab731e00011712d,delivered,2018-03-09 14:50:15,2018-03-09 15:40:39,2018-03-15 00:31:19,2018-04-03 13:28:46,2018-04-02 00:00:00
...,...,...,...,...,...,...,...,...
99396,b3112ca67f3afd4e20cf2ee91fc4f804,6f83c71b6c044fb156d697d4130fe9b5,delivered,2018-08-02 22:46:54,2018-08-02 23:04:06,2018-08-15 17:42:00,2018-08-21 00:03:26,2018-08-16 00:00:00
99397,0fa1fab1d7c1211c824596ed5e111e3c,7f3bd6c94d2daf7b6462d1a894a775b4,delivered,2018-03-13 21:48:57,2018-03-13 22:40:28,2018-03-14 19:27:23,2018-04-05 19:59:49,2018-04-02 00:00:00
99423,38e9133ce29f6bbe35aed9c3863dce01,ad312389a098ceff46ce92c4595c06d0,delivered,2017-10-12 20:54:11,2017-10-14 03:28:24,2017-10-17 17:04:42,2017-11-21 17:06:59,2017-10-31 00:00:00
99425,d692ef54145c9cb3322ec2e5508aa3f4,82ddfcf9438b0cd1117b55ac33184df8,delivered,2018-03-21 19:47:18,2018-03-21 20:05:26,2018-03-22 21:11:58,2018-04-11 00:48:31,2018-04-09 00:00:00
99432,cfa78b997e329a5295b4ee6972c02979,a2f7428f0cafbc8e59f20e1444b67315,delivered,2017-12-20 09:52:41,2017-12-20 10:09:52,2017-12-20 20:25:25,2018-01-26 15:45:14,2018-01-18 00:00:00

In [712]:
orders.duplicated(subset='order_id').sum()

np.int64(0)

In [713]:
products = pd.read_csv('data/olist_products_dataset.csv')

In [714]:
products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [715]:
products.duplicated(subset='product_id').sum()

np.int64(0)

In [716]:
sellers = pd.read_csv('data/olist_sellers_dataset.csv')

In [717]:
sellers

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [718]:
sellers.duplicated(subset='seller_id').sum()

np.int64(0)

In [719]:
category = pd.read_csv('data/product_category_name_translation.csv')

In [720]:
category

,product_category_name,product_category_name_english
0,beleza_saude,health_beauty
1,informatica_acessorios,computers_accessories
2,automotivo,auto
3,cama_mesa_banho,bed_bath_table
4,moveis_decoracao,furniture_decor
5,esporte_lazer,sports_leisure
6,perfumaria,perfumery
7,utilidades_domesticas,housewares
8,telefonia,telephony
9,relogios_presentes,watches_gifts
10,alimentos_bebidas,food_drink
11,bebes,baby
12,papelaria,stationery
13,tablets_impressao_imagem,tablets_printing_image
14,brinquedos,toys
15,telefonia_fixa,fixed_telephony
16,ferramentas_jardim,garden_tools
17,fashion_bolsas_e_acessorios,fashion_bags_accessories
18,eletroportateis,small_appliances
19,consoles_games,consoles_games
20,audio,audio
21,fashion_calcados,fashion_shoes
22,cool_stuff,cool_stuff
23,malas_acessorios,luggage_accessories
24,climatizacao,air_conditioning
25,construcao_ferramentas_construcao,construction_tools_construction
26,moveis_cozinha_area_de_servico_jantar_e_jardim,kitchen_dining_laundry_garden_furniture
27,construcao_ferramentas_jardim,costruction_tools_garden
28,fashion_roupa_masculina,fashion_male_clothing
29,pet_shop,pet_shop
30,moveis_escritorio,office_furniture
31,market_place,market_place
32,eletronicos,electronics
33,eletrodomesticos,home_appliances
34,artigos_de_festas,party_supplies
35,casa_conforto,home_confort
36,construcao_ferramentas_ferramentas,costruction_tools_tools
37,agro_industria_e_comercio,agro_industry_and_commerce
38,moveis_colchao_e_estofado,furniture_mattress_and_upholstery
39,livros_tecnicos,books_technical
40,casa_construcao,home_construction
41,instrumentos_musicais,musical_instruments
42,moveis_sala,furniture_living_room
43,construcao_ferramentas_iluminacao,construction_tools_lights
44,industria_comercio_e_negocios,industry_commerce_and_business
45,alimentos,food
46,artes,art
47,moveis_quarto,furniture_bedroom
48,livros_interesse_geral,books_general_interest
49,construcao_ferramentas_seguranca,construction_tools_safety
50,fashion_underwear_e_moda_praia,fashion_underwear_beach
51,fashion_esporte,fashion_sport
52,sinalizacao_e_seguranca,signaling_and_security
53,pcs,computers
54,artigos_de_natal,christmas_supplies
55,fashion_roupa_feminina,fashio_female_clothing
56,eletrodomesticos_2,home_appliances_2
57,livros_importados,books_imported
58,bebidas,drinks
59,cine_foto,cine_photo
60,la_cuisine,la_cuisine
61,musica,music
62,casa_conforto_2,home_comfort_2
63,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
64,cds_dvds_musicais,cds_dvds_musicals
65,dvds_blu_ray,dvds_blu_ray
66,flores,flowers
67,artes_e_artesanato,arts_and_craftmanship
68,fraldas_higiene,diapers_and_hygiene
69,fashion_roupa_infanto_juvenil,fashion_childrens_clothes
70,seguros_e_servicos,security_and_services

In [721]:
category.duplicated().sum()

np.int64(0)

In [722]:
category.duplicated().sum()

np.int64(0)

In [723]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [724]:
orders.duplicated(subset='order_id').sum()

np.int64(0)

In [725]:
print(len(orders))
print(len(order_items))
print(len(order_reviews))
print(len(order_payments))

99441
112650
99224
103886

In [726]:
order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [727]:
df = orders.merge(order_items, on='order_id', how='left')
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1.0,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1.0,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113420,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1.0,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.90,20.10
113421,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1.0,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.99,65.02
113422,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,1.0,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
113423,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2.0,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
113424,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36

In [728]:
df[df['order_status'] == 'canceled']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
448,1b9ecfe83cdc259250e1a8aca174f0ad,6d6b50b66d79f80827b6d96751528d30,canceled,2018-08-04 14:29:27,2018-08-07 04:10:26,NaN,NaN,2018-08-14 00:00:00,1.0,ad673c1cd02b966e931f9db4fdc34791,9646c3513289980f17226a2fc4720dbd,2018-08-14 04:10:26,25.0,8.34
705,714fb133a6730ab81fa1d3c1b2007291,e3fe72696c4713d64d3c10afe71e75ed,canceled,2018-01-26 21:34:08,2018-01-26 21:58:39,2018-01-29 22:33:25,NaN,2018-02-22 00:00:00,1.0,a0b7d5a992ccda646f2d34e418fff5a0,95f83f51203c626648c875dd41874c7f,2018-02-01 21:58:39,69.9,26.11
1212,3a129877493c8189c59c60eb71d97c29,0913cdce793684e52bbfac69d87e91fd,canceled,2018-01-25 13:34:24,2018-01-25 13:50:20,2018-01-26 21:42:18,NaN,2018-02-23 00:00:00,1.0,7e857e35018e4a05b7d124d1628dc1f0,3fd1e727ba94cfe122d165e176ce7967,2018-01-31 13:50:20,35.9,15.10
1294,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaN,NaN,NaN,2018-09-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
2040,ed3efbd3a87bea76c2812c66a0b32219,191984a8ba4cbb2145acb4fe35b69664,canceled,2018-09-20 13:54:16,NaN,NaN,NaN,2018-10-17 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112793,e49e7ce1471b4693482d40c2bd3ad196,e4e7ab3f449aeb401f0216f86c2104db,canceled,2018-08-07 11:16:28,NaN,NaN,NaN,2018-08-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
113085,6560fb10610771449cb0463c5ba12199,0d07d0a588caf93cc66b7a8aff86d2fe,canceled,2017-10-01 22:26:25,2017-10-01 22:35:22,NaN,NaN,2017-10-27 00:00:00,1.0,dc2410804cf782c5d87dbcd201b74e9b,897060da8b9a21f655304d50fd935913,2017-10-05 22:35:22,150.0,16.81
113086,6560fb10610771449cb0463c5ba12199,0d07d0a588caf93cc66b7a8aff86d2fe,canceled,2017-10-01 22:26:25,2017-10-01 22:35:22,NaN,NaN,2017-10-27 00:00:00,2.0,dc2410804cf782c5d87dbcd201b74e9b,897060da8b9a21f655304d50fd935913,2017-10-05 22:35:22,150.0,16.81
113236,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,NaN,NaN,NaN,2018-10-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
113324,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaN,NaN,NaN,2018-09-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN

In [729]:
df[(df['order_status'] == 'canceled') & (df['order_delivered_carrier_date'].notna())]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
705,714fb133a6730ab81fa1d3c1b2007291,e3fe72696c4713d64d3c10afe71e75ed,canceled,2018-01-26 21:34:08,2018-01-26 21:58:39,2018-01-29 22:33:25,NaN,2018-02-22 00:00:00,1.0,a0b7d5a992ccda646f2d34e418fff5a0,95f83f51203c626648c875dd41874c7f,2018-02-01 21:58:39,69.90,26.11
1212,3a129877493c8189c59c60eb71d97c29,0913cdce793684e52bbfac69d87e91fd,canceled,2018-01-25 13:34:24,2018-01-25 13:50:20,2018-01-26 21:42:18,NaN,2018-02-23 00:00:00,1.0,7e857e35018e4a05b7d124d1628dc1f0,3fd1e727ba94cfe122d165e176ce7967,2018-01-31 13:50:20,35.90,15.10
3284,1950d777989f6a877539f53795b4c3c3,1bccb206de9f0f25adc6871a1bcf77b2,canceled,2018-02-19 19:48:52,2018-02-19 20:56:05,2018-02-20 19:57:13,2018-03-21 22:03:51,2018-03-09 00:00:00,1.0,e435ceb7ced9b8446defd858630454ed,2a61c271b1ac763450d846849783e922,2018-02-23 20:56:05,29.99,14.10
5785,8a9cce19aa49e055f2babb81d5a71c40,f2676ef361959c938b35ecd32321adce,canceled,2018-02-01 10:04:20,2018-02-03 02:52:42,2018-02-05 20:41:28,NaN,2018-02-23 00:00:00,1.0,91f55803717622c017fb93898242a592,5011f0d93373a4c5753adf58ca77af8d,2018-02-08 02:52:42,149.90,17.76
6152,c1049eef89915c6beb3604bf3d6588d7,ed16865bcadcea1a00a928bf418a74bf,canceled,2018-02-05 23:08:11,2018-02-05 23:29:26,2018-02-09 22:13:01,NaN,2018-03-07 00:00:00,1.0,ddceb6eef6af67e9fbbd4c148dbe5fd9,ceaec5548eefc6e23e6607c5435102e7,2018-02-15 23:29:26,215.00,21.00
6214,885935156ba43094f3ae95f3c14e0381,3885c59916b2b261205c303fe0a10abf,canceled,2018-02-02 16:06:44,2018-02-06 04:32:39,2018-02-07 20:48:31,NaN,2018-03-08 00:00:00,1.0,32e18e89237933ebdaaebd78a27e7fa1,ca3bd7cd9f149df75950150d010fe4a2,2018-02-20 02:55:37,26.18,16.60
7535,5b4858f2dcf69731f2285a38829bfa7c,c8223f76047e09bea798462f2f46ffa9,canceled,2018-02-15 20:53:17,2018-02-15 21:06:43,2018-02-16 16:52:52,NaN,2018-03-16 00:00:00,1.0,e86ea175305909ddc0ba25650b2cc7be,dbc22125167c298ef99da25668e1011f,2018-02-21 20:06:43,50.90,17.93
9012,bef875448d5a4f703555d2dd5f8382b5,4a6f6cd7b3fa8d3f9a370adfdad0fa97,canceled,2018-01-23 09:48:56,2018-01-23 10:20:10,2018-01-24 21:04:56,NaN,2018-02-22 00:00:00,1.0,d0b37eae654ad7f4cc8d29d7bab39431,77530e9772f57a62c906e1c21538ab82,2018-01-29 10:20:10,139.90,19.22
9963,dabf2b0e35b423f94618bf965fcb7514,5cdec0bb8cbdf53ffc8fdc212cd247c6,canceled,2016-10-09 00:56:52,2016-10-09 13:36:58,2016-10-13 13:36:59,2016-10-16 14:36:59,2016-11-30 00:00:00,1.0,473795a355d29305c3ea6b156833adf5,620c87c171fb2a6dd6e8bb4dec959fc6,2016-10-13 13:36:59,59.90,0.48
9964,dabf2b0e35b423f94618bf965fcb7514,5cdec0bb8cbdf53ffc8fdc212cd247c6,canceled,2016-10-09 00:56:52,2016-10-09 13:36:58,2016-10-13 13:36:59,2016-10-16 14:36:59,2016-11-30 00:00:00,2.0,7cd29da0653abeb444703cc5a957f479,620c87c171fb2a6dd6e8bb4dec959fc6,2016-10-13 13:36:59,49.90,29.94
16660,2cfc79d9582e9135c0a9b61fa60e6b21,f530197ea86ced9488a03d055e118ebf,canceled,2018-02-19 17:11:34,2018-02-19 17:20:52,2018-02-20 18:58:43,NaN,2018-03-15 00:00:00,1.0,6bd248f93425ceeb625a8a97e2404112,dbc22125167c298ef99da25668e1011f,2018-02-23 17:20:52,59.90,19.66
16756,ba0f1e99132c6f69e4622597e9853599,4624a495981365fa48c8ac2ce5fc3b3d,canceled,2018-01-24 14:16:15,2018-01-24 15:15:57,2018-01-26 18:32:47,NaN,2018-02-21 00:00:00,1.0,656e0eca68dcecf6a31b8ececfabe3e8,6973a06f484aacf400ece213dbf3d946,2018-01-31 15:15:57,89.79,15.38
16784,5abf37ab57e23f69a9c8ab98c4800273,19a045432879d6ddb4fd5611a0e2ba5b,canceled,2018-01-28 00:25:15,2018-01-28 00:36:35,2018-02-01 20:07:57,NaN,2018-02-20 00:00:00,1.0,7ca498260c343bafc4596d101ec12490,2a84855fd20af891be03bc5924d2b453,2018-02-01 00:36:35,158.90,15.87
17638,8caf289ab5d7e3ec7b4522aa22dabbec,dca1d784fd6b8dd1f223bb76482fa053,canceled,2018-02-14 10:37:17,2018-02-14 10:50:27,2018-02-17 00:04:14,NaN,2018-03-07 00:00:00,1.0,e50d5ff1ca7c56933a6f35de967fd2e1,46dc3b2cc0980fb8ec44634e21d2718e,2018-02-20 09:50:27,49.99,14.10
19513,943625151a5d8d00da80e96a90930e03,2953e41dea84f8fe69dc569138b6002f,canceled,2018-02-17 09:59:29,2018-02-17 10:10:26,2018-02-20 16:48:58,NaN,2018-03-06 00:00:00,1.0,f727147ccedba9da38dc2ab8b496a444,9674754b5a0cb32b638cec001178f799,2018-02-22 09:10:26,41.29,9.34
21608,7e30f6ae5435d7c05b487f7b5e1d61ba,c2ca5f569938a5f8a79e1f80f3800e3f,canceled,2018-02-28 13:16:08,2018-02-28 13:35:20,2018-03-02 02:43:53,NaN,2018-03-13 00:00:00,1.0,419cb1b441eda9b92ebd1a1b96090c26,ea8482cd71df3c1969d7b9473ff13abc,2018-03-06 13:31:29,29.99,7.78
22037,b7d469b7eb3c07c6d4b96d505c811fea,5b9d5dfe6b754261741fb68772efed93,canceled,2018-02-03 22:14:25,2018-02-06 04:32:36,2018-02-06 20:46:55,NaN,2018-02-21 00:00:00,1.0,e6fd80a00ebb1a3e0d58a38555fbbf2c,f262cbc1c910c83959f849465454ddd3,2018-02-12 03:51:16,22.99,8.72
24030,7582b8c10039cceafcfe7b13e41a91e2,57bb0f2ff265139687180b2fb387e198,canceled,2018-02-07 14:27:34,2018-02-07 14:35:40,2018-02-10 14:08:59,NaN,2018-03-08 00:00:00,1.0,61509eaebb2d4bd1a7511b1a75703f8c,cca3071e3e9bb7d12640c9fbe2301306,2018-02-13 14:35:40,24.90,15.10
24260,936a199847ccb47438d3ae454d5e18d1,8c587eca721e5478cc6bd17ac3e8cb4c,canceled,2018-02-02 17:42:31,2018-02-02 17:52:12,2018-02-05 13:19:36,NaN,2018-03-09 00:00:00,1.0,3b0f7951038b105522c2d566b54421f7,562fc2f2c2863ab7e79a9e4388a58a14,2018-02-08 17:52:12,29.99,15.10
24714,8f367420ab5fc7305b7383f29ef4ed4e,56be20830570df2c36d2935be6f1e417,canceled,2018-01-30 22:32:13,2018-01-31 20:30:52,2018-02-01 22:47:53,NaN,2018-02-23 00:00:00,1.0,6b3de4cb14325f3a0dafa939520f514e,6560211a19b47992c3666cc44a7e94c0,2018-02-06 20:30:52,69.00,21.28
26939,f3c5d914eec90079a826c2b5ea7fe6bc,078c6672babf4cf39a551e2dcd79229e,canceled,2018-01-26 12:58:01,2018-01-26 13:12:44,2018-01-26 21:45:07,NaN,2018-02-19 00:00:00,1.0,4f130a13e2dd77a6f88f31e7addcec0c,4a3ca9315b744ce9f8e9374361493884,2018-02-01 13:12:44,59.90,12.76
32695,2db84a082bda455eb1da10727e7ca621,12f0a2db64cb3b8ffbe0a340acb99050,canceled,2018-02-02 15:29:05,2018-02-02 16:00:26,2018-02-06 14:54:44,NaN,2018-02-20 00:00:00,1.0,4724ffa427f315c485e39b02e21859b2,955fee9216a65b617aa5c0531780ce60,2018-02-08 16:00:26,12.00,7.78
33912,cd94dbdc801da0cd93b0c8f33663973d,17ba50f54399b61694fbb138a3831d56,canceled,2018-02-21 20:54:45,2018-02-21 21:29:00,2018-02-24 00:21:47,NaN,2018-03-15 00:00:00,1.0,0d85c435fd60b277ffb9e9b0f88f927a,f457c46070d02cadd8a68551231220dd,2018-02-27 21:29:00,68.90,12.61
34139,b8752fc264f1692031237bb715061cc4,217368c0bfd8d50699dfb3f303d4c387,canceled,2018-02-22 16:58:06,2018-02-22 17:15:47,2018-02-23 20:49:02,NaN,2018-03-09 00:00:00,1.0,b8a0d73b2a06e7910d9864dccdb0cda2,620c87c171fb2a6dd6e8bb4dec959fc6,2018-02-28 17:15:47,59.90,8.27
34491,0166cc8756d58b4a30fb49de83527120,19e9dac43eee8df98092482fdce676da,canceled,2018-02-08 21:09:18,2018-02-08 21:27:56,2018-02-09 23:12:30,NaN,2018-02-22 00:00:00,1.0,b59b5899ecf4bcc294a72fdd48adaa94,562fc2f2c2863ab7e79a9e4388a58a14,2018-02-14 21:27:56,29.99,7.78
36254,6b460c25c2bb8e1323536e9e921d04a1,95d2bac8c1d115b9c5291fba7b9186aa,canceled,2018-01-29 16:07:41,2018-01-29 16:36:51,2018-01-30 21:12:59,NaN,2018-03-02 00:00:00,1.0,f731f8587d4088c174397e010cf892a9,cc419e0650a3c5ba77189a1882b7556a,2018-02-07 16:31:39,56.99,15.15
40054,3af427dfb9464cd660ac27292bb5d30b,296fcaa5fafeccd48433a91f4019d99b,canceled,2018-01-30 13:28:14,2018-01-30 14:21:31,2018-02-01 01:58:41,NaN,2018-03-01 00:00:00,1.0,b52385de7f52a8dc46d4195e2f77f965,ac51cac5e20d69ff485a54746488ef48,2018-02-05 14:21:31,59.90,15.17
46066,13a60be94bc36bf7c5f1e0a849cdd6e4,fcd909bbcc659f6100bf2a987d65aca5,canceled,2018-02-19 10:56:33,2018-02-19 11:07:50,2018-02-20 19:19:17,NaN,2018-03-15 00:00:00,1.0,62298e8302e154172f8904c0c2fc620d,5343d0649eca2a983820bfe93fc4d17e,2018-02-23 11:07:50,181.62,17.52
50483,6ad336dba0613cde0e5717f50dc8c669,f6dd94c82d8cf048ef7b4df3ed7a12f7,canceled,2018-01-25 17:18:26,2018-01-25 18:12:14,2018-01-26 20:12:58,NaN,2018-02-23 00:00:00,1.0,ae52eeb8383b94455f0a08b1f88ad002,f457c46070d02cadd8a68551231220dd,2018-01-31 18:12:14,69.90,16.93
51129,8652f7789fe1585b439154b7ae0f4285,0f29ccaad86ee7442d59a69cf4166c6b,canceled,2018-02-20 14:49:42,2018-02-20 15:09:18,2018-02-21 21:23:04,NaN,2018-03-12 00:00:00,1.0,054515fd15bc1a2029f10de97ffa9120,e9779976487b77c6d4ac45f75ec7afe9,2018-02-26 15:09:18,35.00,11.85
54338,24f07a52ca6b749c618b46ddb2e94b8a,2fead6d196da5adf133e4ddb08f51c8c,canceled,2018-01-30 09:39:05,2018-01-30 09:56:17,2018-01-31 23:39:52,NaN,2018-02-21 00:00:00,1.0,e27e689c4ce425f2fe7e2a270fd4d2db,b2479f944e1b90cf8a5de1bbfde284d6,2018-02-05 09:56:17,35.99,12.69
57169,a90966534748634cbb133383bf0eee68,509585871d9505d583be980046b14b8a,canceled,2018-02-01 16:49:17,2018-02-01 17:15:39,2018-02-02 19:26:53,NaN,2018-02-19 00:00:00,1.0,9b6537fef0e6b345c644e019dbe8ac1b,270297ead4c65a6cd2593960d2af6b21,2018-02-07 17:15:39,78.00,8.74
57520,66dbde751178d7674bd09f18b6d25006,6903c9e22ca171ab56f877af3ebaa9dd,canceled,2018-02-05 16:30:33,2018-02-05 16:52:11,2018-02-07 22:52:43,NaN,2018-03-12 00:00:00,1.0,da0bb22eb8eb2bce31a3784570528efb,3d871de0142ce09b7081e2b9d1733cb1,2018-02-14 16:52:11,79.00,38.10
57949,e248283e6b8ba09b05efea1000d9478b,7283505b00797306818c085c6baf0752,canceled,2018-03-03 19:20:13,2018-03-03 20:00:25,2018-03-05 18:18:40,NaN,2018-03-15 00:00:00,1.0,e976121c90262b3c9d173aaf4e03096a,821fb029fc6e495ca4f08a35d51e53a5,2018-03-08 19:30:45,129.90,13.46
60613,e7dfe42bb50a6acce37e168e44260a51,97421afb531a2c357e152626fdecd126,canceled,2018-02-14 01:59:02,2018-02-14 02:10:22,2018-02-14 20:29:03,NaN,2018-03-09 00:00:00,1.0,eed58af018f022f0dbd193a8e81b9321,8d956fec2e4337affcb520f56fd8cbfd,2018-02-20 01:10:22,26.99,14.10
61532,2c0032906c603dcc21cd954828fa77d0,4afea82f984caa99c5946b758f101abd,canceled,2018-02-06 13:44:50,2018-02-06 15:55:40,2018-02-16 20:35:24,NaN,2018-03-12 00:00:00,1.0,d359ac1975cd09111b28c63352a88e18,c1ed9e3daf6154542826a6996af0fb8c,2018-02-12 15:55:40,213.75,36.82
62118,4be69a31714c77604076ab0004055c6c,64f5f567fef8b7faab9a3c95e572cf3c,canceled,2018-01-31 19:30:37,2018-01-31 19:49:47,2018-02-03 02:33:05,NaN,2018-02-22 00:00:00,1.0,cc03fe412a0cde1ba3de9ebbce01adde,0df3984f9dfb3d49ac6366acbd3bbb85,2018-02-06 19:49:47,130.00,15.67
62753,cd408efeda0fdd3fe5f27134bd065001,7183e78211dd520b9a9d1ed9aa888b35,canceled,2018-02-08 22:19:00,2018-02-08 22:30:25,2018-02-09 23:46:35,NaN,2018-02-22 00:00:00,1.0,f0f464c1300173b9ed4aeacf16840936,0be8ff43f22e456b4e0371b2245e4d01,2018-02-14 22:30:25,129.90,9.10
65857,a2714ecbf6eeb3bb9cd7dba6dc1c5e82,5fe0562353e8f0b6c0c6b55cd0f58fe0,canceled,2018-02-14 18:01:38,2018-02-14 18:20:40,2018-02-15 17:27:27,NaN,2018-03-06 00:00:00,1.0,ebb12274522d82caa7dca657873b2ad7,fffd5413c0700ac820c7069d66d98c89,2018-02-20 17:20:40,99.80,33.97
65874,854f8cb8dacdc3abc4cce7a7df6fcc1f,58512a1043fd8047a4f96d5fa665fd2d,canceled,2018-02-02 09:09:27,2018-02-02 09:15:27,2018-02-08 22:06:59,NaN,2018-03-06 00:00:00,1.0,389d119b48cf3043d311335e499d9c6b,1f50f920176fa81dab994f9023523100,2018-02-08 09:15:27,49.90,17.60
66373,770d331c84e5b214bd9dc70a10b829d0,6c57e6119369185e575b36712766b0ef,canceled,2016-10-07 14:52:30,2016-10-07 15:07:10,2016-10-11 15:07:11,2016-10-14 15:07:11,2016-11-29 00:00:00,1.0,eba7488e1c67729f045ab43fac426f2e,620c87c171fb2a6dd6e8bb4dec959fc6,2016-10-11 15:07:11,249.90,14.03
66676,fe9fae71b4fa7d05f1934adc54391f8d,fa9db18cb6fd65d306a4d710799111a8,canceled,2018-02-15 15:28:12,2018-02-15 15:46:54,2018-02-21 19:59:14,NaN,2018-03-07 00:00:00,1.0,06f0e85c7892d5df893f332706340af1,3d871de0142ce09b7081e2b9d1733cb1,2018-02-21 14:46:54,189.00,32.35
67516,881a5cda3b897b035971e3fcfce58aa6,aabb289abf4c3277937c216d0729f36d,canceled,2018-01-31 16:16:21,2018-01-31 16:34:19,2018-02-02 19:04:47,NaN,2018-03-01 00:00:00,1.0,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-02-06 16:31:25,149.00,40.37
67569,8beb59392e21af5eb9547ae1a9938d06,bf609b5741f71697f65ce3852c5d2623,canceled,2016-10-08 20:17:50,2016-10-09 14:34:30,2016-10-14 22:45:26,2016-10-19 18:47:43,2016-11-30 00:00:00,1.0,c66def7098f4d87751f40c3a4855ced1,46dc3b2cc0980fb8ec44634e21d2718e,2016-10-13 14:34:31,99.99,11.23
69932,9c83e5ae8ff2b5cad999c3dc6129a888,b16ed08790d757ebcbc3533101fb1ace,canceled,2018-03-03 09:44:30,2018-03-03 10:20:20,2018-03-05 19:19:03,NaN,2018-03-15 00:00:00,1.0,fb0467f650186a474da44003e623a3c4,6edacfd9f9074789dad6d62ba7950b9c,2018-03-08 10:20:20,9.90,7.78
70294,6cf51ab464bdd9f7b282f5fe72391383,6b8d0ddc6f0be6c4895f69fae60edf2f,canceled,2018-02-27 22:43:39,2018-02-27 22:55:52,2018-02-28 20:07:53,NaN,2018-03-13 00:00:00,1.0,473795a355d29305c3ea6b156833adf5,620c87c171fb2a6dd6e8bb4dec959fc6,2018-03-05 22:55:52,55.90,8.27
70613,2f6492ebb2badd06db511b63ae7d7f55,0ffc8e8c374a394b0715d65963d641f1,canceled,2018-01-20 14:59:28,2018-01-20 15:22:02,2018-01-22 17:09:37,NaN,2018-02-20 00:00:00,1.0,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-25 15:22:02,149.00,40.37
75536,e0b4e92a39bc8b93bc4ff121772819ea,df94e5683581981f437c1986e75c2a29,canceled,2018-02-01 12:21:42,2018-02-01 12:30:36,2018-02-05 10:03:51,NaN,2018-02-19 00:00:00,1.0,64eb8b21706b8e2c733ba16bf02a1537,2c3d56f92f360fb89d849b84e8f50eae,2018-02-07 12:30:36,40.50,13.08
76557,8d171a848151e69e8f090fdbb50d4010,a10afcc34f66a704819e459a8f524ffa,canceled,2018-02-13 14:38:55,2018-02-15 04:07:13,2018-02-16 00:19:33,NaN,2018-03-09 00:00:00,1.0,99a4788cb24856965c36a24e339b6058,4a3ca9315b744ce9f8e9374361493884,2018-02-21 03:07:13,86.90,21.10
80738,cc6c9b89f70b32d7fe075718e0fc58e7,418e9412b396846b861a8c5cb59ba65b,canceled,2018-01-27 10:52:04,2018-01-29 10:52:24,2018-01-30 19:52:55,NaN,2018-03-02 00:00:00,1.0,9da950e8c8c482441f1b93955b21c827,ceaec5548eefc6e23e6607c5435102e7,2018-02-09 10:52:24,215.00,21.00
82600,dba741d70126a95feb85435175370edc,a4426f6a2cfe4a7cea7146f236bf41ae,canceled,2018-01-24 19:18:04,2018-01-24 19:57:20,2018-01-26 20:12:58,NaN,2018-03-05 00:00:00,1.0,70906e04da1eebf3d1b8791bd09ffe85,f457c46070d02cadd8a68551231220dd,2018-01-30 19:57:20,69.90,16.93
82649,cb599c234fc71be7c137179b6d473a30,23534938f44ad51d0de4bf6a56ca1adf,canceled,2018-01-30 20:13:33,2018-01-30 20:33:18,2018-02-01 19:38:42,NaN,2018-02-22 00:00:00,1.0,394e7e390f3282732faa3a73a6033c3a,2a84855fd20af891be03bc5924d2b453,2018-02-05 20:32:15,35.90,15.10
83439,14904245b311483b6886be3c2e717e76,a52ee9f5a35cf680f2aea9dd5fe0941e,canceled,2018-02-12 15:49:38,2018-02-12 16:27:22,2018-02-14 19:25:00,NaN,2018-03-13 00:00:00,1.0,57f2bc497c1a3ebe41ba7a06d78ed159,6560211a19b47992c3666cc44a7e94c0,2018-02-16 16:27:22,55.00,17.67
84706,c7a5d101d4b6ed70eacc97c78158eadd,9d109a169b7b88405b214e976c6039e7,canceled,2018-02-01 19:08:48,2018-02-03 02:53:37,2018-02-06 00:49:39,NaN,2018-03-02 00:00:00,1.0,a62e25e09e05e6faf31d90c6ec1aa3d1,634964b17796e64304cadf1ad3050fb7,2018-02-08 02:53:37,108.00,16.52
84756,d7cc5fcfee9af53fcd78bb47e4e55584,6c081dfe77db2d63f336f33043f0036a,canceled,2018-01-27 10:22:47,2018-01-27 10:36:19,2018-01-30 22:24:41,NaN,2018-02-20 00:00:00,1.0,f40db27e4f52937182f6294988231376,17e34d8224d27a541263c4c64b11a56b,2018-02-01 10:36:19,171.57,13.54
86009,9ec3685b1f21c7dfff4f656392b186dd,952f534f87d6ec6eeaa2cfd1d5987362,canceled,2018-02-20 11:37:45,2018-02-20 11:50:31,2018-02-27 16:17:59,NaN,2018-03-12 00:00:00,1.0,060890b1af8cc031e9dde49cf544f884,8581055ce74af1daba164fdbd55a40de,2018-02-26 11:50:31,89.58,17.34
86827,a8a3eaaf155bc111acb10e0536a9e753,698bbedec1b23581c4ab4aee7270057a,canceled,2018-02-07 12:28:45,2018-02-08 17:05:57,2018-02-09 01:05:58,NaN,2018-03-09 00:00:00,1.0,6cd51331a07b84149502aa6c9c5b536e,c33a5c3c983090c8b78a28e65052a20d,2018-02-14 16:31:27,69.90,16.93
91197,01e7cf79ff6fdb0a65634f714c67dd24,aded241eaa68c31246d82eb3198d4ae3,canceled,2018-02-15 14:58:55,2018-02-15 15:10:35,2018-02-19 18:52:15,NaN,2018-03-07 00:00:00,1.0,32a99bb84ae79a55c0e446afc9310e1e,e5a3438891c0bfdb9394643f95273d8e,2018-02-21 14:10:35,27.30,11.85
92186,d3afe40f7060b3287d948a6bdea42687,8fcf5bb811c9f0ce5cd194b56b5f0ae4,canceled,2018-02-05 22:13:02,2018-02-05 22:30:14,2018-02-06 21:42:51,NaN,2018-02-21 00:00:00,1.0,d44b26fcb399a78808dc8643d991ec14,4371b634e0efc0e22b09b52907d9d469,2018-02-11 22:30:14,26.00,7.78
92638,ab76f54a321a0431ef243b3b6865078b,f89df6ef365783b667b626aeaffc5e2d,canceled,2018-02-04 12:25:42,2018-02-04 12:51:26,2018-02-06 23:21:57,NaN,2018-02-21 00:00:00,1.0,93612dca2cc02cd586ec7e862f2edcbd,de23c3b98a88888289c6f5cc1209054a,2018-02-08 12:51:26,179.00,10.07
94032,4472eca3b65b1dca5e0d59c0e4e0c6bc,5775437e881f0a230649f5c63e1f9241,canceled,2018-02-10 07:39:19,2018-02-10 08:20:22,2018-02-15 22:22:46,NaN,2018-02-26 00:00:00,1.0,d79c712e7afe8f0fd59b749ee1e4fc97,6560211a19b47992c3666cc44a7e94c0,2018-02-15 08:20:22,119.00,8.09
95380,9f0e70e8d046d9e0626bbdaf1aff88c4,6ef5c9f7a060756a678e74a07a3bdfd5,canceled,2018-01-24 12:12:58,2018-01-24 15:16:07,2018-01-25 20:53:51,NaN,2018-03-06 00:00:00,1.0,363a742635cc645c207ce8102de9b837,6c7d50c24b3ccd2fd83b44d8bb34e073,2018-01-30 15:16:07,126.69,39.88
96434,d0fcf3d6dcc18a5c4ac51f06a56ec683,1741b977c920605ffb564947e40cdf0b,canceled,2018-01-31 13:05:16,2018-02-01 11:35:43,2018-02-05 16:47:42,NaN,2018-03-07 00:00:00,1.0,731f32f46216108c900621c487081dcb,f12ff17ad8bbf01ec5c33b17e506649b,2018-02-07 11:35:43,140.00,23.85
96567,6b5ccf5385890198c54fa97afe4812bc,15c523e088107f017c3b74f5874a0f43,canceled,2018-01-30 13:37:28,2018-01-30 13:51:21,2018-01-31 17:22:03,NaN,2018-02-22 00:00:00,1.0,d9545b3e8df3155bca5b302d0f7c3c1c,5b8154610ebb21fb90eb587365e673df,2018-02-05 13:51:21,349.49,28.77
97053,46eb75885eca03736c4188871c0a9ba3,5371cc1698f54400f167d8fc79d6ad93,canceled,2018-01-29 22:54:58,2018-01-29 23:11:24,2018-01-31 22:28:35,NaN,2018-02-23 00:00:00,1.0,ff7fccf8513f360157f0660fe51d1d88,440dd6ab244315c632130ecfb63827b1,2018-02-04 23:11:24,170.00,18.44
100489,ca7296a83aa279afb28c2388a4f48891,daada56f7d2e74dfd291d652b7e03ac2,canceled,2018-02-07 09:48:08,2018-02-07 10:10:17,2018-02-08 23:26:57,NaN,2018-03-07 00:00:00,1.0,2b4609f8948be18874494203496bc318,cc419e0650a3c5ba77189a1882b7556a,2018-02-15 10:10:17,89.99,12.97
103217,0e5e60b0cddf73f60eb73fac19f590cf,52222a646829d54aa33a64283f3b5549,canceled,2018-01-28 21:31:07,2018-01-28 21:39:24,2018-01-29 19:12:01,NaN,2018-02-26 00:00:00,1.0,c4baedd846ed09b85f78a781b522f126,a1043bafd471dff536d0c462352beb48,2018-02-01 21:39:24,120.00,50.71
104802,41c3bd8a34828a1a9ed3bae14a535afe,4e45b6aed6be4fbe9d4a843b9055e19d,canceled,2018-01-23 15:43:48,2018-01-24 02:35:42,2018-01-26 23:07:53,NaN,2018-02-20 00:00:00,1.0,90ebb732ad20456afe8516eb5fbf75f6,bd23da7354813347129d751591d1a6e2,2018-01-30 02:35:42,279.90,26.41
105596,65d1e226dfaeb8cdc42f665422522d14,70fc57eeae292675927697fe03ad3ff5,canceled,2016-10-03 21:01:41,2016-10-04 10:18:57,2016-10-25 12:14:28,2016-11-08 10:58:34,2016-11-25 00:00:00,1.0,9c7bdf67b06b419aefb93cfdfc96c55d,ed49da7cadefc454d6a67de249eab240,2016-10-21 16:24:43,21.50,14.11
106158,7a56ded9b696cca5e892f56f49b1921a,caca87282df2b6fce5e717b93e548b92,canceled,2018-01-28 21:44:00,2018-01-28 21:58:09,2018-01-29 20:21:44,NaN,2018-03-02 00:00:00,1.0,8c292ca193d326152e335d77176746f0,7e1fb0a3ebfb01ffb3a7dae98bf3238d,2018-02-01 21:58:09,150.00,17.49
106228,47e96b5cb6f0592d336b6bf8a817d1c3,9cce7727e7d1d1a738ccc755eae38e93,canceled,2018-01-21 12:44:16,2018-01-22 13:49:10,2018-02-01 00:08:56,NaN,2018-02-19 00:00:00,1.0,db91d5a3b20ec0804d7608ab608bea95,0adac9fbd9a2b63cccaac4f8756c1ca8,2018-01-26 13:49:10,120.90,16.61
107409,c9f06c1229ec7cd4ec9aed55d434b499,fa89053140d09081b3a3a4608a74c083,canceled,2018-02-05 20:26:29,2018-02-05 20:49:48,2018-02-06 19:49:32,NaN,2018-03-01 00:00:00,1.0,8c292ca193d326152e335d77176746f0,7e1fb0a3ebfb01ffb3a7dae98bf3238d,2018-02-09 20:49:48,150.00,12.55
107662,2c45c33d2f9cb8ff8b1c86cc28c11c30,de4caa97afa80c8eeac2ff4c8da5b72e,canceled,2016-10-09 15:39:56,2016-10-10 10:40:49,2016-10-14 10:40:50,2016-11-09 14:53:50,2016-12-08 00:00:00,1.0,e24f73b7631ee3fbb2ab700a9acaa258,0cbcee27c791afa0cdcb08587a2013a8,2016-10-14 10:40:50,135.00,18.51

In [730]:
df[df['order_status']=='unavailable']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
306,8e24261a7e58791d10cb1bf9da94df5c,64a254d30eed42cd0e6c36dddb88adf0,unavailable,2017-11-16 15:09:28,2017-11-16 15:26:57,NaN,NaN,2017-12-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
671,c272bcd21c287498b4883c7512019702,9582c5bbecc65eb568e2c1d839b5cba1,unavailable,2018-01-31 11:31:37,2018-01-31 14:23:50,NaN,NaN,2018-02-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
791,37553832a3a89c9b2db59701c357ca67,7607cd563696c27ede287e515812d528,unavailable,2017-08-14 17:38:02,2017-08-17 00:15:18,NaN,NaN,2017-09-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
850,d57e15fb07fd180f06ab3926b39edcd2,470b93b3f1cde85550fc74cd3a476c78,unavailable,2018-01-08 19:39:03,2018-01-09 07:26:08,NaN,NaN,2018-02-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
1326,2f634e2cebf8c0283e7ef0989f77d217,7353b0fb8e8d9675e3a704c60ca44ebe,unavailable,2017-09-27 20:55:33,2017-09-28 01:32:50,NaN,NaN,2017-10-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113090,6cf5c427fb11bc5fe8abefa86aa7ba0b,91ac14a1e50bc022eeecf0c2ba37006a,unavailable,2017-10-17 10:53:48,2017-10-19 03:12:43,NaN,NaN,2017-10-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
113184,1c7c8ab324927f5b6e52338bd110bef4,95b1767df51d6fa09402267d8de314df,unavailable,2017-12-23 18:48:09,2017-12-23 18:54:22,NaN,NaN,2018-01-19 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
113204,aaab15da689073f8f9aa978a390a69d1,df20748206e4b865b2f14a5eabbfcf34,unavailable,2018-01-16 14:27:59,2018-01-17 03:37:34,NaN,NaN,2018-02-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
113325,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaN,NaN,2017-09-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
113397,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaN,NaN,2017-10-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN

In [731]:
df['order_status'].value_counts()

order_status
delivered      110197
shipped          1186
canceled          706
unavailable       610
invoiced          361
processing        357
created             5
approved            3
Name: count, dtype: int64

In [732]:
df = df.merge(order_payments, on='order_id', how='left')
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,1.0,credit_card,1.0,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,3.0,voucher,1.0,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,2.0,voucher,1.0,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,1.0,boleto,1.0,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,1.0,credit_card,3.0,179.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118429,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1.0,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.90,20.10,1.0,credit_card,3.0,195.00
118430,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1.0,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.99,65.02,1.0,credit_card,5.0,271.01
118431,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,1.0,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59,1.0,credit_card,4.0,441.16
118432,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2.0,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59,1.0,credit_card,4.0,441.16
118433,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36,1.0,debit_card,1.0,86.86

In [733]:
df = df.merge(order_reviews, on='order_id', how='left')
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119138,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1.0,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.90,20.10,1.0,credit_card,3.0,195.00,29bb71b2760d0f876dfa178a76bc4734,4.0,NaN,So uma peça que veio rachado mas tudo bem rs,2018-03-01 00:00:00,2018-03-02 17:50:01
119139,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1.0,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.99,65.02,1.0,credit_card,5.0,271.01,371579771219f6db2d830d50805977bb,5.0,NaN,Foi entregue antes do prazo.,2017-09-22 00:00:00,2017-09-22 23:10:57
119140,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,1.0,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59,1.0,credit_card,4.0,441.16,8ab6855b9fe9b812cd03a480a25058a1,2.0,NaN,Foi entregue somente 1. Quero saber do outro p...,2018-01-26 00:00:00,2018-01-27 09:16:56
119141,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2.0,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59,1.0,credit_card,4.0,441.16,8ab6855b9fe9b812cd03a480a25058a1,2.0,NaN,Foi entregue somente 1. Quero saber do outro p...,2018-01-26 00:00:00,2018-01-27 09:16:56
119142,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36,1.0,debit_card,1.0,86.86,dc9c59b4688062c25758c2be4cafc523,5.0,NaN,NaN,2018-03-17 00:00:00,2018-03-17 16:33:31

In [734]:
dup = df[df.duplicated(subset='order_id',keep=False)].sort_values(by='order_id')
dup

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
64593,0008288aa423d2a3f00fcb17cd7d8719,2355af7c75e7c98b43a87b2a7f210dc5,delivered,2018-02-13 22:10:21,2018-02-15 03:55:52,2018-02-20 18:23:28,2018-02-26 13:55:22,2018-03-06 00:00:00,2.0,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37,1.0,boleto,1.0,126.54,5505c1cce299b1e0b3f8e4b428417362,5.0,NaN,NaN,2018-02-27 00:00:00,2018-03-02 10:20:40
64592,0008288aa423d2a3f00fcb17cd7d8719,2355af7c75e7c98b43a87b2a7f210dc5,delivered,2018-02-13 22:10:21,2018-02-15 03:55:52,2018-02-20 18:23:28,2018-02-26 13:55:22,2018-03-06 00:00:00,1.0,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37,1.0,boleto,1.0,126.54,5505c1cce299b1e0b3f8e4b428417362,5.0,NaN,NaN,2018-02-27 00:00:00,2018-03-02 10:20:40
43491,00143d0f86d6fbd9f9b38ab440ac16f5,2e45292979b9b2700ea09560eeb0f803,delivered,2017-10-16 15:29:43,2017-10-16 16:07:52,2017-10-16 23:04:43,2017-10-27 18:43:56,2017-11-06 00:00:00,1.0,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10,1.0,credit_card,1.0,109.29,NaN,NaN,NaN,NaN,NaN,NaN
43492,00143d0f86d6fbd9f9b38ab440ac16f5,2e45292979b9b2700ea09560eeb0f803,delivered,2017-10-16 15:29:43,2017-10-16 16:07:52,2017-10-16 23:04:43,2017-10-27 18:43:56,2017-11-06 00:00:00,2.0,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10,1.0,credit_card,1.0,109.29,NaN,NaN,NaN,NaN,NaN,NaN
43493,00143d0f86d6fbd9f9b38ab440ac16f5,2e45292979b9b2700ea09560eeb0f803,delivered,2017-10-16 15:29:43,2017-10-16 16:07:52,2017-10-16 23:04:43,2017-10-27 18:43:56,2017-11-06 00:00:00,3.0,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10,1.0,credit_card,1.0,109.29,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101889,fff8287bbae429a99bb7e8c21d151c41,6c1e92a209dbf868706caa831090941e,delivered,2018-03-17 12:11:45,2018-03-17 12:29:22,2018-03-21 19:22:25,2018-04-07 10:07:48,2018-04-19 00:00:00,1.0,bee2e070c39f3dd2f6883a17a5f0da45,4e922959ae960d389249c378d1c939f5,2018-03-27 12:29:22,180.00,48.14,1.0,credit_card,4.0,456.28,2b97d83f7c2b3a3b4285174e77379fbc,5.0,NaN,Tudo ok,2018-04-08 00:00:00,2018-04-12 20:25:15
74072,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27 00:00:00,3.0,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19,1.0,boleto,1.0,356.76,269edb5280ad1f999b5043c93cc4e845,4.0,NaN,NaN,2017-11-18 00:00:00,2017-11-18 22:50:50
74071,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27 00:00:00,2.0,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19,1.0,boleto,1.0,356.76,269edb5280ad1f999b5043c93cc4e845,4.0,NaN,NaN,2017-11-18 00:00:00,2017-11-18 22:50:50
74070,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27 00:00:00,1.0,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19,1.0,boleto,1.0,356.76,269edb5280ad1f999b5043c93cc4e845,4.0,NaN,NaN,2017-11-18 00:00:00,2017-11-18 22:50:50
74073,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27 00:00:00,4.0,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19,1.0,boleto,1.0,356.76,269edb5280ad1f999b5043c93cc4e845,4.0,NaN,NaN,2017-11-18 00:00:00,2017-11-18 22:50:50

In [735]:
df = df.merge(products, on='product_id', how='left').merge(category, on='product_category_name', how='left')
df = df.sort_values(by='order_id')
df[['order_purchase_timestamp','order_approved_at','shipping_limit_date','order_delivered_carrier_date','order_delivered_customer_date']]

,order_purchase_timestamp,order_approved_at,shipping_limit_date,order_delivered_carrier_date,order_delivered_customer_date
102015,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48
85965,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-03 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24
7455,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-18 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16
26952,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-15 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39
6200,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-13 13:57:51,2017-02-16 09:46:09,2017-03-01 16:42:31
...,...,...,...,...,...
95124,2018-04-23 13:57:06,2018-04-25 04:11:01,2018-05-02 04:11:01,2018-04-25 12:09:00,2018-05-10 22:56:40
83874,2018-07-14 10:26:46,2018-07-17 04:31:48,2018-07-20 04:31:48,2018-07-17 08:05:00,2018-07-23 20:31:55
63072,2017-10-23 17:07:56,2017-10-24 17:14:25,2017-10-30 17:14:25,2017-10-26 15:13:14,2017-10-28 12:22:22
71587,2017-08-14 23:02:59,2017-08-15 00:04:32,2017-08-21 00:04:32,2017-08-15 19:02:53,2017-08-16 21:59:40
71432,2018-06-09 17:00:18,2018-06-09 17:10:13,2018-06-12 17:10:13,2018-06-11 14:11:00,2018-06-14 17:56:26

In [736]:
df.sort_values(by=['order_id','order_item_id'])[['order_id','order_item_id','price','freight_value','payment_sequential','payment_installments','payment_value']]

,order_id,order_item_id,price,freight_value,payment_sequential,payment_installments,payment_value
102015,00010242fe8c5a6d1ba2dd792cb16214,1.0,58.90,13.29,1.0,2.0,72.19
85965,00018f77f2f0320c557190d7a144bdd3,1.0,239.90,19.93,1.0,3.0,259.83
7455,000229ec398224ef6ca0657da4fc703e,1.0,199.00,17.87,1.0,5.0,216.87
26952,00024acbcdf0a6daa1e931b038114c75,1.0,12.99,12.79,1.0,2.0,25.78
6200,00042b26cf59d7ce69dfabb4e55b4fd9,1.0,199.90,18.14,1.0,3.0,218.04
...,...,...,...,...,...,...,...
95124,fffc94f6ce00a00581880bf54a75a037,1.0,299.99,43.41,1.0,1.0,343.40
83874,fffcd46ef2263f404302a634eb57f7eb,1.0,350.00,36.53,1.0,1.0,386.53
63072,fffce4705a9662cd70adb13d4a31832d,1.0,99.90,16.95,1.0,3.0,116.85
71587,fffe18544ffabc95dfada21779c9644f,1.0,55.99,8.72,1.0,3.0,64.71
71432,fffe41c64501cc87c801fd61db3f6244,1.0,43.00,12.79,1.0,1.0,55.79

In [737]:
(49.9 + 13.37) * 2

126.53999999999999

In [738]:
df['product_category_name_english'].value_counts()

product_category_name_english
bed_bath_table                             11988
health_beauty                              10032
sports_leisure                              9004
furniture_decor                             8832
computers_accessories                       8150
housewares                                  7380
watches_gifts                               6213
telephony                                   4726
garden_tools                                4590
auto                                        4400
toys                                        4281
cool_stuff                                  3999
perfumery                                   3589
baby                                        3204
electronics                                 2846
stationery                                  2625
fashion_bags_accessories                    2170
pet_shop                                    2030
office_furniture                            1788
consoles_games                              1192
luggage_accessories                         1163
construction_tools_construction              955
home_appliances                              826
musical_instruments                          719
small_appliances                             705
home_construction                            635
books_general_interest                       565
furniture_living_room                        532
food                                         526
home_confort                                 478
drinks                                       390
audio                                        381
market_place                                 332
construction_tools_lights                    314
air_conditioning                             302
kitchen_dining_laundry_garden_furniture      299
food_drink                                   291
fashion_shoes                                278
fixed_telephony                              272
books_technical                              272
industry_commerce_and_business               272
home_appliances_2                            270
agro_industry_and_commerce                   252
costruction_tools_garden                     247
computers                                    220
art                                          219
signaling_and_security                       201
construction_tools_safety                    199
christmas_supplies                           155
fashion_male_clothing                        145
fashion_underwear_beach                      144
furniture_bedroom                            126
costruction_tools_tools                      105
tablets_printing_image                        87
small_appliances_home_oven_and_coffee         78
cine_photo                                    74
dvds_blu_ray                                  71
books_imported                                62
fashio_female_clothing                        50
party_supplies                                46
furniture_mattress_and_upholstery             41
music                                         40
diapers_and_hygiene                           39
flowers                                       33
home_comfort_2                                31
fashion_sport                                 31
arts_and_craftmanship                         24
la_cuisine                                    16
cds_dvds_musicals                             14
fashion_childrens_clothes                      8
security_and_services                          2
Name: count, dtype: int64

In [739]:
df['review_score'].value_counts()

review_score
5.0    66343
4.0    22319
1.0    15428
3.0     9894
2.0     4162
Name: count, dtype: int64

In [740]:
df['price']

102015     58.90
85965     239.90
7455      199.00
26952      12.99
6200      199.90
           ...
95124     299.99
83874     350.00
63072      99.90
71587      55.99
71432      43.00
Name: price, Length: 119143, dtype: float64

In [741]:
df[df.duplicated(subset='order_id',keep=False)]
# 같은 order_id에 대해서 각 행의 payment_value를 합한 것이 price + freight_value

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
64592,0008288aa423d2a3f00fcb17cd7d8719,2355af7c75e7c98b43a87b2a7f210dc5,delivered,2018-02-13 22:10:21,2018-02-15 03:55:52,2018-02-20 18:23:28,2018-02-26 13:55:22,2018-03-06 00:00:00,1.0,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37,1.0,boleto,1.0,126.54,5505c1cce299b1e0b3f8e4b428417362,5.0,NaN,NaN,2018-02-27 00:00:00,2018-03-02 10:20:40,ferramentas_jardim,57.0,366.0,2.0,1650.0,30.0,22.0,30.0,garden_tools
64593,0008288aa423d2a3f00fcb17cd7d8719,2355af7c75e7c98b43a87b2a7f210dc5,delivered,2018-02-13 22:10:21,2018-02-15 03:55:52,2018-02-20 18:23:28,2018-02-26 13:55:22,2018-03-06 00:00:00,2.0,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37,1.0,boleto,1.0,126.54,5505c1cce299b1e0b3f8e4b428417362,5.0,NaN,NaN,2018-02-27 00:00:00,2018-03-02 10:20:40,ferramentas_jardim,57.0,366.0,2.0,1650.0,30.0,22.0,30.0,garden_tools
43493,00143d0f86d6fbd9f9b38ab440ac16f5,2e45292979b9b2700ea09560eeb0f803,delivered,2017-10-16 15:29:43,2017-10-16 16:07:52,2017-10-16 23:04:43,2017-10-27 18:43:56,2017-11-06 00:00:00,3.0,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10,1.0,credit_card,1.0,109.29,NaN,NaN,NaN,NaN,NaN,NaN,esporte_lazer,52.0,1153.0,1.0,180.0,17.0,11.0,14.0,sports_leisure
43492,00143d0f86d6fbd9f9b38ab440ac16f5,2e45292979b9b2700ea09560eeb0f803,delivered,2017-10-16 15:29:43,2017-10-16 16:07:52,2017-10-16 23:04:43,2017-10-27 18:43:56,2017-11-06 00:00:00,2.0,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10,1.0,credit_card,1.0,109.29,NaN,NaN,NaN,NaN,NaN,NaN,esporte_lazer,52.0,1153.0,1.0,180.0,17.0,11.0,14.0,sports_leisure
43491,00143d0f86d6fbd9f9b38ab440ac16f5,2e45292979b9b2700ea09560eeb0f803,delivered,2017-10-16 15:29:43,2017-10-16 16:07:52,2017-10-16 23:04:43,2017-10-27 18:43:56,2017-11-06 00:00:00,1.0,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10,1.0,credit_card,1.0,109.29,NaN,NaN,NaN,NaN,NaN,NaN,esporte_lazer,52.0,1153.0,1.0,180.0,17.0,11.0,14.0,sports_leisure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101889,fff8287bbae429a99bb7e8c21d151c41,6c1e92a209dbf868706caa831090941e,delivered,2018-03-17 12:11:45,2018-03-17 12:29:22,2018-03-21 19:22:25,2018-04-07 10:07:48,2018-04-19 00:00:00,1.0,bee2e070c39f3dd2f6883a17a5f0da45,4e922959ae960d389249c378d1c939f5,2018-03-27 12:29:22,180.00,48.14,1.0,credit_card,4.0,456.28,2b97d83f7c2b3a3b4285174e77379fbc,5.0,NaN,Tudo ok,2018-04-08 00:00:00,2018-04-12 20:25:15,informatica_acessorios,53.0,871.0,4.0,175.0,20.0,20.0,20.0,computers_accessories
74070,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27 00:00:00,1.0,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19,1.0,boleto,1.0,356.76,269edb5280ad1f999b5043c93cc4e845,4.0,NaN,NaN,2017-11-18 00:00:00,2017-11-18 22:50:50,relogios_presentes,41.0,1159.0,4.0,350.0,16.0,14.0,11.0,watches_gifts
74071,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27 00:00:00,2.0,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19,1.0,boleto,1.0,356.76,269edb5280ad1f999b5043c93cc4e845,4.0,NaN,NaN,2017-11-18 00:00:00,2017-11-18 22:50:50,relogios_presentes,41.0,1159.0,4.0,350.0,16.0,14.0,11.0,watches_gifts
74072,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27 00:00:00,3.0,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19,1.0,boleto,1.0,356.76,269edb5280ad1f999b5043c93cc4e845,4.0,NaN,NaN,2017-11-18 00:00:00,2017-11-18 22:50:50,relogios_presentes,41.0,1159.0,4.0,350.0,16.0,14.0,11.0,watches_gifts
74073,fffb9224b6fc7c43ebb0904318b10b5f,4d3abb73ceb86353aeadbe698aa9d5cb,delivered,2017-10-27 16:51:00,2017-10-28 02:55:58,2017-11-10 19:31:52,2017-11-17 19:41:42,2017-11-27 00:00:00,4.0,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19,1.0,boleto,1.0,356.76,269edb5280ad1f999b5043c93cc4e845,4.0,NaN,NaN,2017-11-18 00:00:00,2017-11-18 22:50:50,relogios_presentes,41.0,1159.0,4.0,350.0,16.0,14.0,11.0,watches_gifts

In [742]:
df['payment_installments'].value_counts()

payment_installments
1.0     59446
2.0     13838
3.0     11889
4.0      8072
10.0     6976
5.0      6097
8.0      5120
6.0      4674
7.0      1848
9.0       739
12.0      168
15.0       93
18.0       38
24.0       34
11.0       26
20.0       21
13.0       19
14.0       16
17.0        8
16.0        7
21.0        6
0.0         3
23.0        1
22.0        1
Name: count, dtype: int64

In [743]:
df[df['order_id']=='744bade1fcf9ff3f31d860ace076d422']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
76229,744bade1fcf9ff3f31d860ace076d422,5e5794daaa13f73e2f1cdb4114529843,delivered,2018-04-22 11:34:42,2018-04-24 19:04:46,2018-04-24 03:14:34,2018-04-27 20:55:28,2018-05-16 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,7202e2ba20579a9bd1acb29e61fe71f6,2018-04-26 12:31:06,45.9,12.79,2.0,credit_card,0.0,58.69,c56b4b7042f417e70d3dc5340deb23fe,5.0,NaN,NaN,2018-04-28 00:00:00,2018-04-29 17:43:50,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony

In [744]:
df[df['product_id']=='0cf573090c66bb30ac5e53c82bdb0403']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
93422,02358a9949662b292e80635305dea78b,e69e27216b375e2c7e1be6298b051bf2,delivered,2017-05-15 16:59:19,2017-05-17 04:05:19,2017-05-17 09:52:11,2017-05-23 14:18:00,2017-06-19 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,99eaacc9e6046db1c82b163c5f84869f,2017-05-23 04:05:19,59.0,25.69,1.0,boleto,1.0,84.69,edc7ac11e8e280a6898c6035d6b4e058,5.0,NaN,NaN,2017-05-24 00:00:00,2017-05-25 18:29:43,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
115911,138d22c05c5e456f19bdc7dcf09b89aa,7b3f5e33cc06406a59d69da8df6494e0,delivered,2017-03-22 06:13:55,2017-03-22 06:13:55,2017-03-24 16:03:40,2017-03-31 13:23:12,2017-04-10 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,99eaacc9e6046db1c82b163c5f84869f,2017-03-28 06:13:55,59.0,11.02,1.0,credit_card,1.0,70.02,f356ff7e7a22b827d568440b45425bd1,5.0,NaN,NaN,2017-04-01 00:00:00,2017-04-04 01:42:58,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
35347,14e80e4600a8d7fafeb635d6d4ef7151,235dbacd9cbfaee70bf092cecac8b62d,delivered,2018-04-16 17:21:17,2018-04-18 02:31:43,2018-04-18 18:22:19,2018-05-02 12:32:49,2018-05-21 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,7202e2ba20579a9bd1acb29e61fe71f6,2018-04-24 02:31:20,45.9,18.23,1.0,boleto,1.0,64.13,b2045e02e3693728c7b192939dd2a24a,4.0,tudo certo,Com esse produto tudo certo,2018-05-03 00:00:00,2018-05-04 14:25:13,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
70637,2882e815bbb59314e58194adf2fe61e3,1cc48f15ae29278a2ae5fd4ace4c97fd,delivered,2018-04-24 23:49:23,2018-04-25 00:11:09,2018-04-26 12:58:00,2018-04-30 22:59:28,2018-05-17 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,7202e2ba20579a9bd1acb29e61fe71f6,2018-05-02 00:11:09,45.9,12.79,5.0,voucher,1.0,5.95,e9eb4cc483f607317940e646bdbe98fd,5.0,NaN,NaN,2018-05-01 00:00:00,2018-05-02 12:58:44,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
70641,2882e815bbb59314e58194adf2fe61e3,1cc48f15ae29278a2ae5fd4ace4c97fd,delivered,2018-04-24 23:49:23,2018-04-25 00:11:09,2018-04-26 12:58:00,2018-04-30 22:59:28,2018-05-17 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,7202e2ba20579a9bd1acb29e61fe71f6,2018-05-02 00:11:09,45.9,12.79,4.0,voucher,1.0,13.18,e9eb4cc483f607317940e646bdbe98fd,5.0,NaN,NaN,2018-05-01 00:00:00,2018-05-02 12:58:44,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
70639,2882e815bbb59314e58194adf2fe61e3,1cc48f15ae29278a2ae5fd4ace4c97fd,delivered,2018-04-24 23:49:23,2018-04-25 00:11:09,2018-04-26 12:58:00,2018-04-30 22:59:28,2018-05-17 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,7202e2ba20579a9bd1acb29e61fe71f6,2018-05-02 00:11:09,45.9,12.79,3.0,voucher,1.0,13.18,e9eb4cc483f607317940e646bdbe98fd,5.0,NaN,NaN,2018-05-01 00:00:00,2018-05-02 12:58:44,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
70638,2882e815bbb59314e58194adf2fe61e3,1cc48f15ae29278a2ae5fd4ace4c97fd,delivered,2018-04-24 23:49:23,2018-04-25 00:11:09,2018-04-26 12:58:00,2018-04-30 22:59:28,2018-05-17 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,7202e2ba20579a9bd1acb29e61fe71f6,2018-05-02 00:11:09,45.9,12.79,2.0,voucher,1.0,13.18,e9eb4cc483f607317940e646bdbe98fd,5.0,NaN,NaN,2018-05-01 00:00:00,2018-05-02 12:58:44,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
70640,2882e815bbb59314e58194adf2fe61e3,1cc48f15ae29278a2ae5fd4ace4c97fd,delivered,2018-04-24 23:49:23,2018-04-25 00:11:09,2018-04-26 12:58:00,2018-04-30 22:59:28,2018-05-17 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,7202e2ba20579a9bd1acb29e61fe71f6,2018-05-02 00:11:09,45.9,12.79,1.0,voucher,1.0,13.20,e9eb4cc483f607317940e646bdbe98fd,5.0,NaN,NaN,2018-05-01 00:00:00,2018-05-02 12:58:44,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
4442,5361ae7742cca11bdce02eba111d345a,822d89ae169a34fc33eddc98e2e90e23,delivered,2017-03-22 08:40:31,2017-03-22 08:40:31,2017-03-24 16:03:39,2017-03-28 12:27:00,2017-04-10 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,99eaacc9e6046db1c82b163c5f84869f,2017-03-28 08:40:31,59.0,11.02,1.0,credit_card,1.0,70.02,be747dea4b76cbf0068d7570ca791219,5.0,NaN,NaN,2017-03-29 00:00:00,2017-04-03 00:01:08,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
84396,662157b4251f62efae6f4ff7525c4961,5455991bd713bcaa1aa748d420f7e034,delivered,2017-03-27 14:09:19,2017-03-27 14:42:33,2017-03-28 18:42:29,2017-04-03 11:52:52,2017-04-13 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,99eaacc9e6046db1c82b163c5f84869f,2017-03-31 14:42:33,59.0,11.02,1.0,debit_card,1.0,70.02,2cc37195f30332b22b69e29ea606a601,5.0,NaN,NaN,2017-04-04 00:00:00,2017-04-04 21:18:17,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
76229,744bade1fcf9ff3f31d860ace076d422,5e5794daaa13f73e2f1cdb4114529843,delivered,2018-04-22 11:34:42,2018-04-24 19:04:46,2018-04-24 03:14:34,2018-04-27 20:55:28,2018-05-16 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,7202e2ba20579a9bd1acb29e61fe71f6,2018-04-26 12:31:06,45.9,12.79,2.0,credit_card,0.0,58.69,c56b4b7042f417e70d3dc5340deb23fe,5.0,NaN,NaN,2018-04-28 00:00:00,2018-04-29 17:43:50,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
20648,80897d5d4e8f07edd515daa585302e6b,1df202848b9d575c667c29519f38249e,delivered,2017-04-11 10:31:19,2017-04-11 10:42:30,2017-04-17 08:57:48,2017-05-10 06:42:16,2017-05-03 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,99eaacc9e6046db1c82b163c5f84869f,2017-04-17 10:42:30,59.0,11.02,1.0,credit_card,1.0,70.02,4d3d6c6bc22992f85fc3b2552d4ccef9,2.0,NaN,NaN,2017-05-05 00:00:00,2017-05-05 16:56:13,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
87208,9e4490f14f9c72dc40d107d497fa7573,60631e57e82948629e88dc2599c8df8e,delivered,2017-03-22 15:56:01,2017-03-24 01:42:51,2017-03-24 16:03:38,2017-03-31 16:58:12,2017-04-10 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,99eaacc9e6046db1c82b163c5f84869f,2017-03-30 01:42:51,59.0,11.02,1.0,boleto,1.0,70.02,b5bc37944193ed6f23aa5c130c003c54,5.0,NaN,NaN,2017-04-01 00:00:00,2017-04-02 04:49:46,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
17988,bca2c019b40c204248a56707eabb2a2c,abd1cbc79c4a8e29986772e6ac493431,delivered,2017-03-29 20:06:38,2017-03-30 10:22:37,2017-03-30 18:46:09,2017-04-07 16:28:24,2017-04-20 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,99eaacc9e6046db1c82b163c5f84869f,2017-04-05 10:22:37,59.0,14.58,1.0,credit_card,6.0,73.58,9df0b33c4b129cb21ad140d2b9092cc0,4.0,NaN,NaN,2017-04-08 00:00:00,2017-04-09 01:00:11,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
105748,bfef81581affa2b4c59018ed748cd663,396092ad2cd63fcdcc4beebcce77460e,delivered,2017-03-28 13:49:04,2017-03-28 14:02:29,2017-03-28 18:43:17,2017-04-11 10:31:08,2017-04-19 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,99eaacc9e6046db1c82b163c5f84869f,2017-04-03 14:02:29,59.0,14.58,1.0,credit_card,1.0,73.58,b7df3d69a3fae60c9e9761f50a4c39b6,5.0,NaN,Entregue no prazo,2017-04-12 00:00:00,2017-04-12 21:07:58,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
15119,ce4c70f737d1a9edba23290f6031d076,3e4b0745edd000022ba7bbeb4918104c,delivered,2018-04-04 10:39:30,2018-04-05 02:28:06,2018-04-06 02:46:29,2018-04-10 16:37:57,2018-04-26 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,7202e2ba20579a9bd1acb29e61fe71f6,2018-04-11 02:28:06,45.9,12.79,1.0,boleto,1.0,117.38,86b80d753c3fb8a6e0558c1e7a58dced,5.0,NaN,Eu recomendo esse parceiro entrega no prazo e ...,2018-04-11 00:00:00,2018-04-12 10:30:14,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
15120,ce4c70f737d1a9edba23290f6031d076,3e4b0745edd000022ba7bbeb4918104c,delivered,2018-04-04 10:39:30,2018-04-05 02:28:06,2018-04-06 02:46:29,2018-04-10 16:37:57,2018-04-26 00:00:00,2.0,0cf573090c66bb30ac5e53c82bdb0403,7202e2ba20579a9bd1acb29e61fe71f6,2018-04-11 02:28:06,45.9,12.79,1.0,boleto,1.0,117.38,86b80d753c3fb8a6e0558c1e7a58dced,5.0,NaN,Eu recomendo esse parceiro entrega no prazo e ...,2018-04-11 00:00:00,2018-04-12 10:30:14,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
9715,d8f9df1fea3171b46193d6a185d1fec9,8f08be4bff90a008ab13026acdcfc338,delivered,2018-04-04 23:35:19,2018-04-04 23:50:17,2018-04-06 03:06:30,2018-04-11 18:19:10,2018-04-26 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,7202e2ba20579a9bd1acb29e61fe71f6,2018-04-10 23:50:17,45.9,12.79,1.0,credit_card,1.0,58.69,7dc0ebe690de6c7dc4ee86eaf7e3e3e4,5.0,NaN,NaN,2018-04-12 00:00:00,2018-04-12 22:06:19,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
42661,d90c74ac81e1df6eb8fa862f94aeb132,4a961874c6f36b766aa4663a8ad1fba6,delivered,2017-05-01 19:02:24,2017-05-03 11:35:33,2017-05-04 10:11:30,2017-05-15 10:59:47,2017-05-25 00:00:00,2.0,0cf573090c66bb30ac5e53c82bdb0403,99eaacc9e6046db1c82b163c5f84869f,2017-05-09 11:32:26,59.0,14.58,1.0,boleto,1.0,147.16,0b2e69e684be72769363b9078ce2e0c7,5.0,NaN,NaN,2017-05-16 00:00:00,2017-05-20 21:53:11,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
42660,d90c74ac81e1df6eb8fa862f94aeb132,4a961874c6f36b766aa4663a8ad1fba6,delivered,2017-05-01 19:02:24,2017-05-03 11:35:33,2017-05-04 10:11:30,2017-05-15 10:59:47,2017-05-25 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,99eaacc9e6046db1c82b163c5f84869f,2017-05-09 11:32:26,59.0,14.58,1.0,boleto,1.0,147.16,0b2e69e684be72769363b9078ce2e0c7,5.0,NaN,NaN,2017-05-16 00:00:00,2017-05-20 21:53:11,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony
41239,fb5ae559d53a2c9ad1f34f3b98085457,e7e417314d3929e21b06799c5ee30e19,delivered,2018-05-14 11:43:47,2018-05-14 12:16:50,2018-05-17 14:36:00,2018-05-21 17:03:48,2018-06-01 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,7202e2ba20579a9bd1acb29e61fe71f6,2018-05-18 12:16:50,45.9,13.14,1.0,credit_card,1.0,59.04,d75858e01e908acf6df943d37dc15372,5.0,NaN,NaN,2018-05-22 00:00:00,2018-05-22 20:42:18,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony

In [745]:
df[df['payment_installments']==0]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
79378,1a57108394169c0b47d8f876acc9ba2d,48ebb06cf56dba9d009230cc751bb195,delivered,2018-05-15 16:25:14,2018-05-15 16:36:52,2018-05-17 12:37:00,2018-05-24 15:45:41,2018-06-06 00:00:00,2.0,db35a562fb6ba63e19fa42a15349dc04,282f23a9769b2690c5dda22e316f9941,2018-05-18 16:31:54,41.69,23.28,2.0,credit_card,0.0,129.94,bc5dca6c957c328b1cbff760b0841fd2,5.0,NaN,NaN,2018-05-25 00:00:00,2018-05-26 00:24:28,utilidades_domesticas,56.0,235.0,1.0,500.0,23.0,11.0,23.0,housewares
79377,1a57108394169c0b47d8f876acc9ba2d,48ebb06cf56dba9d009230cc751bb195,delivered,2018-05-15 16:25:14,2018-05-15 16:36:52,2018-05-17 12:37:00,2018-05-24 15:45:41,2018-06-06 00:00:00,1.0,db35a562fb6ba63e19fa42a15349dc04,282f23a9769b2690c5dda22e316f9941,2018-05-18 16:31:54,41.69,23.28,2.0,credit_card,0.0,129.94,bc5dca6c957c328b1cbff760b0841fd2,5.0,NaN,NaN,2018-05-25 00:00:00,2018-05-26 00:24:28,utilidades_domesticas,56.0,235.0,1.0,500.0,23.0,11.0,23.0,housewares
76229,744bade1fcf9ff3f31d860ace076d422,5e5794daaa13f73e2f1cdb4114529843,delivered,2018-04-22 11:34:42,2018-04-24 19:04:46,2018-04-24 03:14:34,2018-04-27 20:55:28,2018-05-16 00:00:00,1.0,0cf573090c66bb30ac5e53c82bdb0403,7202e2ba20579a9bd1acb29e61fe71f6,2018-04-26 12:31:06,45.90,12.79,2.0,credit_card,0.0,58.69,c56b4b7042f417e70d3dc5340deb23fe,5.0,NaN,NaN,2018-04-28 00:00:00,2018-04-29 17:43:50,telefonia,26.0,108.0,1.0,128.0,15.0,8.0,13.0,telephony

In [746]:
df[df['payment_installments']>1]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
102015,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29 00:00:00,1.0,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,1.0,credit_card,2.0,72.19,97ca439bc427b48bc1cd7177abe71365,5.0,NaN,"Perfeito, produto entregue antes do combinado.",2017-09-21 00:00:00,2017-09-22 10:57:03,cool_stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0,cool_stuff
85965,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15 00:00:00,1.0,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,1.0,credit_card,3.0,259.83,7b07bacd811c4117b742569b04ce3580,4.0,NaN,NaN,2017-05-13 00:00:00,2017-05-15 11:34:13,pet_shop,56.0,239.0,2.0,30000.0,50.0,30.0,40.0,pet_shop
7455,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05 00:00:00,1.0,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,1.0,credit_card,5.0,216.87,0c5b33dea94867d1ac402749e5438e8b,5.0,NaN,Chegou antes do prazo previsto e o produto sur...,2018-01-23 00:00:00,2018-01-23 16:06:31,moveis_decoracao,59.0,695.0,2.0,3050.0,33.0,13.0,33.0,furniture_decor
26952,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20 00:00:00,1.0,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,1.0,credit_card,2.0,25.78,f4028d019cb58564807486a6aaf33817,4.0,NaN,NaN,2018-08-15 00:00:00,2018-08-15 16:39:01,perfumaria,42.0,480.0,1.0,200.0,16.0,10.0,15.0,perfumery
6200,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17 00:00:00,1.0,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,1.0,credit_card,3.0,218.04,940144190dcba6351888cafa43f3a3a5,5.0,NaN,Gostei pois veio no prazo determinado .,2017-03-02 00:00:00,2017-03-03 10:54:59,ferramentas_jardim,59.0,409.0,1.0,3750.0,35.0,40.0,30.0,garden_tools
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101889,fff8287bbae429a99bb7e8c21d151c41,6c1e92a209dbf868706caa831090941e,delivered,2018-03-17 12:11:45,2018-03-17 12:29:22,2018-03-21 19:22:25,2018-04-07 10:07:48,2018-04-19 00:00:00,1.0,bee2e070c39f3dd2f6883a17a5f0da45,4e922959ae960d389249c378d1c939f5,2018-03-27 12:29:22,180.00,48.14,1.0,credit_card,4.0,456.28,2b97d83f7c2b3a3b4285174e77379fbc,5.0,NaN,Tudo ok,2018-04-08 00:00:00,2018-04-12 20:25:15,informatica_acessorios,53.0,871.0,4.0,175.0,20.0,20.0,20.0,computers_accessories
59764,fffa82886406ccf10c7b4e35c4ff2788,a5201e1a6d71a8d21e869151bd5b4085,delivered,2017-12-18 16:33:07,2017-12-18 17:33:04,2017-12-20 18:55:00,2018-01-08 18:23:10,2018-01-24 00:00:00,1.0,bbe7651fef80287a816ead73f065fc4b,8f2ce03f928b567e3d56181ae20ae952,2017-12-22 17:31:42,229.90,44.02,1.0,credit_card,7.0,273.92,b49f4e0ca71a9801d56ff4e47cff1ded,4.0,NaN,NaN,2018-01-09 00:00:00,2018-01-11 23:56:38,esporte_lazer,32.0,280.0,2.0,2700.0,60.0,15.0,15.0,sports_leisure
116127,fffbee3b5462987e66fb49b1c5411df2,11a0e041ea6e7e21856d2689b64e7f3a,delivered,2018-06-19 09:27:48,2018-06-19 09:58:03,2018-06-29 13:46:00,2018-07-05 17:51:08,2018-07-23 00:00:00,1.0,6f0169f259bb0ff432bfff7d829b9946,213b25e6f54661939f11710a6fddb871,2018-06-28 09:58:03,119.85,20.03,1.0,credit_card,3.0,139.88,a614fd24fbd8348db190dc720530e101,5.0,NaN,NaN,2018-07-06 00:00:00,2018-07-09 10:41:17,casa_construcao,58.0,918.0,6.0,1050.0,16.0,20.0,16.0,home_construction
63072,fffce4705a9662cd70adb13d4a31832d,29309aa813182aaddc9b259e31b870e6,delivered,2017-10-23 17:07:56,2017-10-24 17:14:25,2017-10-26 15:13:14,2017-10-28 12:22:22,2017-11-10 00:00:00,1.0,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,1.0,credit_card,3.0,116.85,dbdd81cd59a1a9f94a10a990b4d48dce,5.0,NaN,NaN,2017-10-29 00:00:00,2017-10-29 21:33:52,esporte_lazer,43.0,869.0,1.0,967.0,21.0,24.0,19.0,sports_leisure
71587,fffe18544ffabc95dfada21779c9644f,b5e6afd5a41800fdf401e0272ca74655,delivered,2017-08-14 23:02:59,2017-08-15 00:04:32,2017-08-15 19:02:53,2017-08-16 21:59:40,2017-08-25 00:00:00,1.0,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,1.0,credit_card,3.0,64.71,fba117c9ac40d41ca7be54741f471303,5.0,NaN,Recebi o produto antes do prazo e corretamente.,2017-08-17 00:00:00,2017-08-18 12:24:05,informatica_acessorios,56.0,1306.0,1.0,100.0,20.0,20.0,20.0,computers_accessories